name: repo-manager
description: Automated repository administrator
author: mattsb42
inputs:
    github-token:
        description: GitHub authentication token
        required: true
    github-repository:
        description: GitHub repository to update
        required: false
    config-file:
        description: Location of config file in repo
        default: .github/settings.yml
        required: false
    debug:
        description: Enables debug logging if set
        required: false
runs:
    using: docker
    image: Dockerfile
