# This workflow runs integration tests
name: integration tests

on:
    pull_request:
        branches:
            - master

jobs:
    integ-tests:
        if: github.base_ref == 'master' && github.head_ref == 'development'
        runs-on: ubuntu-latest
        steps:
            -   uses: actions/checkout@v2
            -   uses: actions/setup-python@v1
                with:
                    python-version: 3.x
            -   run: |
                    python -m pip install --upgrade pip
                    pip install --upgrade -r ci-requirements.txt
            -   name: run tests
                env:
                    TOXENV: integ
                    GITHUB_TOKEN: ${{ secrets.ADMIN_TOKEN }}
                run: tox -- -vv
